### PR TITLE
Build drawer menu

### PR DESCRIPTION
**Pull request by madrilene**
- make drawer menu the default
- adjust the CSS for the drawer menu

### CODE REVIEW

**Comment by madrilene** [comment]
This works, but I'm not yet sure if it's a solid solution

**Comment by tobie** [comment]
Still the same problem for me on iOS.

**Comment by tobie** [comment]
The other solution I has seen was this: https://dev.to/tongrhj/the-mistake-developers-make-when-coding-a-hamburger-menu-1deg

**Comment by madrilene** [comment]
Can you give me your iPhone model / iOS version? I have to check if the `:has()` pseudo-class is supported, and if that's not the case, use a JS solution instead.

**Comment by tobie** [comment]
Well, I'd want to make sure it works for the bulk of iOS users, not just me. :)

**Comment by madrilene** [comment]
Sure! That's why I need to investigate this further. To pinpoint the problem to the usage of `:has()` and in consequence check on the other places where has might be used, and the implications if its not supported.

**Comment by madrilene** [comment]
Tested it with your device on Browserstack`:has()` was not the problem, but the overflow-y property. `:has()` is widely supported now, since version 15.4 for Safari. 
https://caniuse.com/css-has

Instead I opted for removing the no JS fallback, so users with older Browser versions get a good experience. 
https://caniuse.com/?search=css-media-scripting

**Comment by tobie** [comment]
Yeah, I have stopped paying attention to browser support a long while ago. :)

**Comment by madrilene** [comment]
Shall we merge that?

**Pull request merged**
